spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/anonymous_board
    username: root
    password: insa
  devtools:
    remote:
      restart:
        enabled: true



